# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-23 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icds_reports', '0058_new_agg_ccs_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregatesqlprofile',
            name='latest_aggregration',
            field=models.DateField(null=True),
        ),
    ]
